global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'app_metrics'
    static_configs:
      - targets: ['my-backend-95433363736.us-central1.run.app']
    scheme: https

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
