name: Deploy Backend to Azure

on:
  push:
    branches: [ main ]
    paths: 
      - 'server/**'  # Only deploy when backend changes

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-backend

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Login to GitHub Container Registry (recommended over DockerHub)
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: .  # Root directory where Dockerfile is
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        labels: |
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: attend-sure-backend  # Create separate app for backend
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        configuration-file: |
          {
            "appSettings": [
              {
                "name": "WEBSITES_ENABLE_APP_SERVICE_STORAGE",
                "value": "false"
              },
              {
                "name": "MONGODB_URI",
                "value": "${{ secrets.MONGODB_URI }}"
              },
              {
                "name": "NODE_ENV",
                "value": "production"
              },
              {
                "name": "PORT",
                "value": "80"
              },
              {
                "name": "WEBSITES_PORT",
                "value": "80"
              }
            ]
          }